name: noe
channels:
  - conda-forge
  - defaults
  - omnia
dependencies:
  - python=3.7.4
  - numpy
  - scipy
  - scikit-learn=0.20.0
  - pandas=1.2.2
  - rdkit>=2021.09.1
  - pip
  - openmm=7.5.1
  - pdbfixer
  - mdtraj
  - tqdm
  - notebook
  - nglview
  - joblib
  - ase
  - parmed
  - openmoltools
  #- openff-toolkit
  - openforcefield=0.6.0
  - pip:
    - versioneer
    - setuptools